import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Keypair, Networks } from '@stellar/stellar-sdk';
import { contract as stellarContract } from '@stellar/stellar-sdk';
import {
  Client as IdentityVerifierClient,
  networks as identityVerifierNetworks,
  IdentityRole,
} from '../packages/identity_verifier/dist/index.js';
import { KycStatus, KybStatus, UserRole } from 'prisma/generated/prisma/client';
import type { UserWithRelations } from 'src/users/users.repository';

/**
 * BlockchainService — Soroban smart-contract bridge.
 *
 * Syncs KYC / KYB verification results from Sumsub into the on-chain
 * `identity-verifier` contract. When a user's KYC or KYB status reaches
 * COMPLETED (Sumsub `applicantReviewed` → GREEN), we call
 * `set_identity(user, verified=true, country_code, role, operator)` so the
 * contract's identity registry reflects the off-chain verification.
 *
 * The `operator` is the admin Stellar account derived from `ADMIN_SECRET`
 * (the raw 32-byte ed25519 seed, hex-encoded). The same admin that
 * initialized the `identity-verifier` contract must sign the
 * `set_identity` transaction.
 *
 * Contract bindings live in `src/packages/identity_verifier/` (generated by
 * `stellar contract bindings typescript`). The contract id + network
 * passphrase are baked into the bindings' `networks` constant.
 */

/** Soroban RPC endpoint for Stellar Testnet. */
const SOROBAN_RPC_URL =
  process.env.SOROBAN_RPC_URL ?? 'https://soroban-testnet.stellar.org';

/** Network passphrase — must match the contract deployment network. */
const NETWORK_PASSPHRASE = Networks.TESTNET;

@Injectable()
export class BlockchainService implements OnModuleInit {
  private readonly logger = new Logger(BlockchainService.name);

  /** Admin Keypair derived from ADMIN_SECRET. */
  private adminKeypair!: Keypair;

  /** Admin's Stellar public key (G...) — used as `operator` / source account. */
  private adminAddress!: string;

  /** Identity-verifier contract client. */
  private identityClient!: IdentityVerifierClient;

  constructor(private readonly config: ConfigService) {}

  onModuleInit() {
    const adminSecret = this.config.getOrThrow<string>('ADMIN_SECRET');

    // ADMIN_SECRET can be either a Stellar secret key (S...) or a raw
    // 32-byte ed25519 seed (hex string, 64 chars).
    if (adminSecret.startsWith('S')) {
      this.adminKeypair = Keypair.fromSecret(adminSecret);
    } else {
      const seed = Buffer.from(adminSecret, 'hex');
      if (seed.length !== 32) {
        throw new Error(
          `ADMIN_SECRET must be a Stellar secret key (S...) or a 32-byte hex string (got ${seed.length} bytes)`,
        );
      }
      this.adminKeypair = Keypair.fromRawEd25519Seed(seed);
    }
    this.adminAddress = this.adminKeypair.publicKey();
    this.logger.log(`Admin address derived: ${this.adminAddress}`);

    // Build the identity-verifier contract client with the admin as the
    // source account + signer.
    const net = identityVerifierNetworks.testnet;
    this.identityClient = new IdentityVerifierClient({
      contractId: net.contractId,
      networkPassphrase: NETWORK_PASSPHRASE,
      rpcUrl: SOROBAN_RPC_URL,
      publicKey: this.adminAddress,
      ...stellarContract.basicNodeSigner(this.adminKeypair, NETWORK_PASSPHRASE),
    });

    this.logger.log(
      `IdentityVerifier client ready → contract ${net.contractId}`,
    );
  }

  /**
   * Sync a user's verification status to the on-chain identity-verifier.
   *
   * Called from the Sumsub webhook handler when `kycStatus` or `kybStatus`
   * transitions to COMPLETED or REJECTED. Only COMPLETED triggers
   * `verified = true`; REJECTED triggers `verified = false` so any existing
   * on-chain identity record is revoked.
   *
   * @param user  — the user record (must have a wallet address)
   * @param type  — 'kyc' or 'kyb'
   * @param verified — whether the user passed verification
   * @param countryCode — ISO 3166-1 alpha-2 country code (defaults to '' if unknown)
   */
  async syncIdentity(
    user: UserWithRelations,
    type: 'kyc' | 'kyb',
    verified: boolean,
    countryCode: string,
  ): Promise<void> {
    if (!user.wallet?.address) {
      this.logger.warn(
        `User ${user.id} has no wallet address — skipping on-chain sync`,
      );
      return;
    }

    const role =
      type === 'kyb' || user.role === UserRole.SHIPPING_COMPANY
        ? IdentityRole.KYB
        : IdentityRole.KYC;

    this.logger.log(
      `Syncing identity on-chain → user=${user.id} addr=${user.wallet.address} verified=${verified} role=${type.toUpperCase()}`,
    );

    try {
      const tx = await this.identityClient.set_identity({
        user: user.wallet.address,
        verified,
        country_code: countryCode || '',
        role,
        operator: this.adminAddress,
      });

      const sent = await tx.signAndSend();
      const hash = sent.sendTransactionResponse?.hash;
      const status = sent.getTransactionResponse?.status;

      this.logger.log(
        `Identity synced on-chain → hash=${hash ?? 'pending'} status=${status ?? 'submitted'}`,
      );
    } catch (error) {
      this.logger.error(
        `On-chain identity sync failed for user ${user.id}`,
        error instanceof Error ? error.stack : String(error),
      );
      // Don't throw — webhook should still return 200 to Sumsub so it doesn't
      // retry. The off-chain DB is already updated; on-chain sync can be
      // retried later via a reconciliation job.
    }
  }

  /**
   * Convenience: map a KYC status change to an on-chain sync call.
   * Only called when kycStatus transitions to COMPLETED or REJECTED.
   */
  async syncKycStatus(
    user: UserWithRelations,
    newStatus: KycStatus,
  ): Promise<void> {
    if (newStatus === KycStatus.COMPLETED) {
      await this.syncIdentity(user, 'kyc', true, user.companyCountry ?? '');
    } else if (newStatus === KycStatus.REJECTED) {
      await this.syncIdentity(user, 'kyc', false, user.companyCountry ?? '');
    }
  }

  /**
   * Convenience: map a KYB status change to an on-chain sync call.
   * Only called when kybStatus transitions to COMPLETED or REJECTED.
   */
  async syncKybStatus(
    user: UserWithRelations,
    newStatus: KybStatus,
  ): Promise<void> {
    if (newStatus === KybStatus.COMPLETED) {
      await this.syncIdentity(user, 'kyb', true, user.companyCountry ?? '');
    } else if (newStatus === KybStatus.REJECTED) {
      await this.syncIdentity(user, 'kyb', false, user.companyCountry ?? '');
    }
  }
}
