import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  Keypair,
  Networks,
  rpc as stellarRpc,
  contract as stellarContract,
  TransactionBuilder,
  Transaction,
  Contract,
  Address,
  nativeToScVal,
  BASE_FEE,
} from '@stellar/stellar-sdk';
import {
  Client as IdentityVerifierClient,
  networks as identityVerifierNetworks,
  IdentityRole,
} from 'src/packages/identity_verifier/dist/index.js';
import {
  Client as FactoryClient,
  networks as factoryNetworks,
  RWA,
  RWAStatus,
} from 'src/packages/factory/dist/index.js';
import { KycStatus, KybStatus, UserRole } from 'prisma/generated/prisma/client';
import type { UserWithRelations } from 'src/users/users.repository';
import { createHash, randomBytes } from 'node:crypto';
import { xdr, StrKey } from '@stellar/stellar-sdk';

/** Soroban RPC endpoint for Stellar Testnet. */
const SOROBAN_RPC_URL =
  process.env.SOROBAN_RPC_URL ?? 'https://soroban-testnet.stellar.org';

/** Network passphrase — must match the contract deployment network. */
const NETWORK_PASSPHRASE = Networks.TESTNET;

// ─── Constants (mirrors scripts/src/lib.ts) ──────────────────────────────

export const LEDGERS_PER_DAY = 17_280;
export const LEDGERS_PER_HOUR = 720;
export const USDC_SCALE = 10_000_000n;

// ─── Permit message helpers (from scripts/src/lib.ts) ────────────────────

export function buildPermitMessage(opts: {
  contractAddress: string;
  action: 1 | 2;
  accountAddress: string;
  amount: bigint;
  nonce: bigint;
  deadline: number;
}): Uint8Array {
  const { contractAddress, action, accountAddress, amount, nonce, deadline } =
    opts;

  const parts: Uint8Array[] = [];
  parts.push(new TextEncoder().encode('SEP57_PERMIT_V1'));
  parts.push(new Uint8Array([action]));
  parts.push(encodeLenPrefixedStr(contractAddress));
  parts.push(encodeLenPrefixedStr(accountAddress));
  parts.push(bigIntToBEBytes(amount, 16));
  parts.push(bigIntToBEBytes(nonce, 8));
  parts.push(uint32ToBEBytes(deadline));
  return concat(parts);
}

function encodeLenPrefixedStr(s: string): Uint8Array {
  const bytes = new TextEncoder().encode(s);
  const out = new Uint8Array(4 + bytes.length);
  new DataView(out.buffer).setUint32(0, bytes.length, false);
  out.set(bytes, 4);
  return out;
}

function bigIntToBEBytes(n: bigint, byteLen: number): Uint8Array {
  const out = new Uint8Array(byteLen);
  let v = n;
  for (let i = byteLen - 1; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

function uint32ToBEBytes(n: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, n >>> 0, false);
  return out;
}

function concat(arrs: Uint8Array[]): Uint8Array {
  const total = arrs.reduce((s, a) => s + a.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const a of arrs) {
    out.set(a, off);
    off += a.length;
  }
  return out;
}

export function nextNonce(): bigint {
  const bytes = crypto.getRandomValues(new Uint8Array(8));
  let n = 0n;
  for (const b of bytes) n = (n << 8n) | BigInt(b);
  return n & 0xffffffffffffffffn;
}

export function predictTokenAddress(
  factoryAddress: string,
  salt: Uint8Array,
): string {
  if (salt.length !== 32)
    throw new Error(`salt must be 32 bytes, got ${salt.length}`);
  const deployerRaw = StrKey.decodeContract(factoryAddress);
  const networkId = createHash('sha256')
    .update(Buffer.from(NETWORK_PASSPHRASE))
    .digest();
  const fromAddress = new xdr.ContractIdPreimageFromAddress({
    address: xdr.ScAddress.scAddressTypeContract(
      deployerRaw as unknown as xdr.Hash,
    ),
    salt: Buffer.from(salt),
  });
  const contractIdPreimage =
    xdr.ContractIdPreimage.contractIdPreimageFromAddress(fromAddress);
  const preimageCid = new xdr.HashIdPreimageContractId({
    networkId,
    contractIdPreimage,
  });
  const preimage = xdr.HashIdPreimage.envelopeTypeContractId(preimageCid);
  const id = createHash('sha256').update(preimage.toXDR()).digest();
  return StrKey.encodeContract(id);
}

/**
 * BlockchainService — Soroban smart-contract bridge.
 *
 * Syncs KYC / KYB verification results from Sumsub into the on-chain
 * `identity-verifier` contract. When a user's KYC or KYB status reaches
 * COMPLETED (Sumsub `applicantReviewed` → GREEN), we call
 * `set_identity(user, verified=true, country_code, role, operator)` so the
 * contract's identity registry reflects the off-chain verification.
 *
 * The `operator` is the admin Stellar account derived from `ADMIN_SECRET`
 * (the raw 32-byte ed25519 seed, hex-encoded). The same admin that
 * initialized the `identity-verifier` contract must sign the
 * `set_identity` transaction.
 *
 * Contract bindings live in `src/packages/identity_verifier/` (generated by
 * `stellar contract bindings typescript`). The contract id + network
 * passphrase are baked into the bindings' `networks` constant.
 */

@Injectable()
export class BlockchainService implements OnModuleInit {
  private readonly logger = new Logger(BlockchainService.name);

  /** Admin Keypair derived from ADMIN_SECRET. */
  private adminKeypair!: Keypair;

  /** Admin's Stellar public key (G...) — used as `operator` / source account. */
  private adminAddress!: string;

  /** Identity-verifier contract client. */
  private identityClient!: IdentityVerifierClient;

  /** Factory contract client (RWA tokenization). */
  private factoryClient!: FactoryClient;

  /** Factory contract ID (C...). */
  private factoryContractId!: string;

  /** Soroban RPC server instance (shared across all callers). */
  private rpcServer!: stellarRpc.Server;

  constructor(private readonly config: ConfigService) {}

  onModuleInit() {
    const adminSecret = this.config.getOrThrow<string>('ADMIN_SECRET');

    // ADMIN_SECRET can be either a Stellar secret key (S...) or a raw
    // 32-byte ed25519 seed (hex string, 64 chars).
    if (adminSecret.startsWith('S')) {
      this.adminKeypair = Keypair.fromSecret(adminSecret);
    } else {
      const seed = Buffer.from(adminSecret, 'hex');
      if (seed.length !== 32) {
        throw new Error(
          `ADMIN_SECRET must be a Stellar secret key (S...) or a 32-byte hex string (got ${seed.length} bytes)`,
        );
      }
      this.adminKeypair = Keypair.fromRawEd25519Seed(seed);
    }
    this.adminAddress = this.adminKeypair.publicKey();
    this.logger.log(`Admin address derived: ${this.adminAddress}`);

    // Build the identity-verifier contract client with the admin as the
    // source account + signer.
    const net = identityVerifierNetworks.testnet;
    this.identityClient = new IdentityVerifierClient({
      contractId: net.contractId,
      networkPassphrase: NETWORK_PASSPHRASE,
      rpcUrl: SOROBAN_RPC_URL,
      publicKey: this.adminAddress,
      ...stellarContract.basicNodeSigner(this.adminKeypair, NETWORK_PASSPHRASE),
    });

    this.logger.log(
      `IdentityVerifier client ready → contract ${net.contractId}`,
    );

    // Build the factory contract client — contract ID comes from the
    // generated bindings (networks.testnet.contractId), not from an env var.
    const factoryNet = factoryNetworks.testnet;
    this.factoryContractId = factoryNet.contractId;
    this.factoryClient = new FactoryClient({
      contractId: factoryNet.contractId,
      networkPassphrase: NETWORK_PASSPHRASE,
      rpcUrl: SOROBAN_RPC_URL,
      publicKey: this.adminAddress,
      ...stellarContract.basicNodeSigner(this.adminKeypair, NETWORK_PASSPHRASE),
    });

    // Soroban RPC server (used by events listener + transaction submission).
    this.rpcServer = new stellarRpc.Server(SOROBAN_RPC_URL);

    this.logger.log(
      `Factory client ready → contract ${this.factoryContractId}`,
    );
  }

  /**
   * Sync a user's verification status to the on-chain identity-verifier.
   *
   * Called from the Sumsub webhook handler when `kycStatus` or `kybStatus`
   * transitions to COMPLETED or REJECTED. Only COMPLETED triggers
   * `verified = true`; REJECTED triggers `verified = false` so any existing
   * on-chain identity record is revoked.
   *
   * @param user  — the user record (must have a wallet address)
   * @param type  — 'kyc' or 'kyb'
   * @param verified — whether the user passed verification
   * @param countryCode — ISO 3166-1 alpha-2 country code (defaults to '' if unknown)
   */
  async syncIdentity(
    user: UserWithRelations,
    type: 'kyc' | 'kyb',
    verified: boolean,
    countryCode: string,
  ): Promise<void> {
    if (!user.wallet?.address) {
      this.logger.warn(
        `User ${user.id} has no wallet address — skipping on-chain sync`,
      );
      return;
    }

    const role =
      type === 'kyb' || user.role === UserRole.SHIPPING_COMPANY
        ? IdentityRole.KYB
        : IdentityRole.KYC;

    this.logger.log(
      `Syncing identity on-chain → user=${user.id} addr=${user.wallet.address} verified=${verified} role=${type.toUpperCase()}`,
    );

    try {
      const tx = await this.identityClient.set_identity({
        user: user.wallet.address,
        verified,
        country_code: countryCode || '',
        role,
        operator: this.adminAddress,
      });

      const sent = await tx.signAndSend();
      const hash = sent.sendTransactionResponse?.hash;
      const status = sent.getTransactionResponse?.status;

      this.logger.log(
        `Identity synced on-chain → hash=${hash ?? 'pending'} status=${status ?? 'submitted'}`,
      );
    } catch (error) {
      this.logger.error(
        `On-chain identity sync failed for user ${user.id}`,
        error instanceof Error ? error.stack : String(error),
      );
      // Don't throw — webhook should still return 200 to Sumsub so it doesn't
      // retry. The off-chain DB is already updated; on-chain sync can be
      // retried later via a reconciliation job.
    }
  }

  /**
   * Convenience: map a KYC status change to an on-chain sync call.
   * Only called when kycStatus transitions to COMPLETED or REJECTED.
   */
  async syncKycStatus(
    user: UserWithRelations,
    newStatus: KycStatus,
  ): Promise<void> {
    if (newStatus === KycStatus.COMPLETED) {
      await this.syncIdentity(user, 'kyc', true, user.companyCountry ?? '');
    } else if (newStatus === KycStatus.REJECTED) {
      await this.syncIdentity(user, 'kyc', false, user.companyCountry ?? '');
    }
  }

  /**
   * Convenience: map a KYB status change to an on-chain sync call.
   * Only called when kybStatus transitions to COMPLETED or REJECTED.
   */
  async syncKybStatus(
    user: UserWithRelations,
    newStatus: KybStatus,
  ): Promise<void> {
    if (newStatus === KybStatus.COMPLETED) {
      await this.syncIdentity(user, 'kyb', true, user.companyCountry ?? '');
    } else if (newStatus === KybStatus.REJECTED) {
      await this.syncIdentity(user, 'kyb', false, user.companyCountry ?? '');
    }
  }

  // ─── Factory / RWA methods ────────────────────────────────────────────

  /** The factory contract client (for building/simulating transactions). */
  get factory(): FactoryClient {
    return this.factoryClient;
  }

  /** The factory contract ID (C...). */
  get factoryContractAddress(): string {
    return this.factoryContractId;
  }

  /**
   * Build a factory client scoped to a shipper's wallet address.
   * Used for transactions where the shipper is the source account
   * (e.g. create_rwa_token) so Soroban require_auth(shipper) passes.
   * No signer is attached — the tx is signed externally via DFNS.
   */
  factoryForShipper(shipperAddress: string): FactoryClient {
    return new FactoryClient({
      contractId: this.factoryContractId,
      networkPassphrase: NETWORK_PASSPHRASE,
      rpcUrl: SOROBAN_RPC_URL,
      publicKey: shipperAddress,
      // No signer — tx will be signed by DFNS on the frontend
    });
  }

  /** The admin Keypair (used to sign permit messages). */
  get adminKey(): Keypair {
    return this.adminKeypair;
  }

  /** The admin's Stellar public key (G...). */
  get adminPublicKey(): string {
    return this.adminAddress;
  }

  /** The network passphrase. */
  get networkPassphrase(): string {
    return NETWORK_PASSPHRASE;
  }

  /** The Soroban RPC server instance. */
  get rpc(): stellarRpc.Server {
    return this.rpcServer;
  }

  /** Fetch the latest ledger sequence from Soroban RPC. */
  async getLatestLedger(): Promise<number> {
    const resp = await this.rpcServer.getLatestLedger();
    return resp.sequence;
  }

  /**
   * Submit a signed Soroban transaction (after DFNS signing on the frontend).
   * Decodes the XDR and sends it to Soroban RPC.
   */
  async submitTransaction(signedTxXdr: string): Promise<{
    hash: string;
    status: string;
    errorResultXdr: string | null;
  }> {
    const tx = TransactionBuilder.fromXDR(
      signedTxXdr,
      NETWORK_PASSPHRASE,
    ) as Transaction;

    this.logger.debug('Submitting tx', {
      source: tx.source,
      fee: tx.fee,
      operations: tx.operations.length,
      hasSorobanData: !!tx.toXDR().includes('soroban'),
      seqNum: tx.sequence,
    });

    const sent = await this.rpcServer.sendTransaction(tx);

    this.logger.debug('sendTransaction result', {
      status: sent.status,
      hash: sent.hash,
      errorResultXdr: sent.errorResult?.toXDR('base64') ?? null,
    });

    // `sendTransaction` only tells us the tx was accepted into the mempool
    // (PENDING); it never returns SUCCESS. Reject immediately on ERROR /
    // TRY_AGAIN_LATER, otherwise poll `getTransaction` until the tx lands in a
    // ledger so callers see the real on-chain outcome (and, for multi-step
    // flows, so downstream simulations observe the applied state).
    if (sent.status === 'ERROR') {
      return {
        hash: sent.hash,
        status: 'FAILED',
        errorResultXdr: sent.errorResult?.toXDR('base64') ?? null,
      };
    }

    const final = await this.rpcServer.pollTransaction(sent.hash, {
      attempts: 20,
    });

    this.logger.debug('pollTransaction result', {
      status: final.status,
      hash: sent.hash,
    });

    const errorResultXdr =
      final.status === stellarRpc.Api.GetTransactionStatus.FAILED
        ? (final.resultXdr?.toXDR('base64') ?? null)
        : null;

    return {
      hash: sent.hash,
      status: final.status,
      errorResultXdr,
    };
  }

  /** Read the USDC (payment token) contract address from the factory. */
  async getUsdcAddress(): Promise<string> {
    const tx = await this.factoryClient.usdc();
    return tx.result;
  }

  /** Read the protocol fee (bps) configured on the factory. */
  async getProtocolFeeBps(): Promise<bigint> {
    const tx = await this.factoryClient.protocol_fee_bps();
    return BigInt(tx.result);
  }

  /**
   * Rewrite any `sorobanCredentialsAddress` auth entries to
   * `sorobanCredentialsSourceAccount`.
   *
   * Our transactions always use the account that must authorize (the shipper)
   * as the transaction source, and it is signed at the envelope level by DFNS.
   * Source-account credentials are satisfied by that envelope signature, so we
   * swap the simulation-produced address credentials — which would otherwise
   * need their own separate Soroban auth signature — for source-account ones.
   */
  convertShipperAuthToSourceAccount(txXdr: string): string {
    const env = xdr.TransactionEnvelope.fromXDR(txXdr, 'base64');
    const tx = env.v1().tx();
    for (const op of tx.operations()) {
      if (op.body().switch().name !== 'invokeHostFunction') continue;
      const auth = op.body().invokeHostFunctionOp().auth();
      for (const entry of auth) {
        if (entry.credentials().switch().name === 'sorobanCredentialsAddress') {
          entry.credentials(
            xdr.SorobanCredentials.sorobanCredentialsSourceAccount(),
          );
        }
      }
    }
    return env.toXDR('base64');
  }

  /**
   * Build an assembled USDC `approve(owner, spender, amount, expiration_ledger)`
   * transaction with `owner` as the source account, ready for DFNS signing.
   * Returns the transaction XDR (with source-account auth credentials).
   */
  async buildApproveTx(opts: {
    ownerAddress: string;
    spenderAddress: string;
    amount: bigint;
    expirationLedger: number;
  }): Promise<string> {
    const usdcAddress = await this.getUsdcAddress();
    const account = await this.rpcServer.getAccount(opts.ownerAddress);
    const tokenContract = new Contract(usdcAddress);

    const raw = new TransactionBuilder(account, {
      fee: BASE_FEE,
      networkPassphrase: NETWORK_PASSPHRASE,
    })
      .addOperation(
        tokenContract.call(
          'approve',
          nativeToScVal(Address.fromString(opts.ownerAddress), {
            type: 'address',
          }),
          nativeToScVal(Address.fromString(opts.spenderAddress), {
            type: 'address',
          }),
          nativeToScVal(opts.amount, { type: 'i128' }),
          nativeToScVal(opts.expirationLedger, { type: 'u32' }),
        ),
      )
      .setTimeout(300)
      .build();

    const sim = await this.rpcServer.simulateTransaction(raw);
    if (stellarRpc.Api.isSimulationError(sim)) {
      throw new Error(`approve simulation failed: ${sim.error}`);
    }

    const assembled = stellarRpc.assembleTransaction(raw, sim).build();
    return this.convertShipperAuthToSourceAccount(assembled.toXDR());
  }

  /**
   * Sign a SEP57 mint permit with the admin keypair.
   * Returns the signature bytes.
   */
  signMintPermit(opts: {
    contractAddress: string;
    accountAddress: string;
    amount: bigint;
    nonce: bigint;
    deadline: number;
  }): Uint8Array {
    const message = buildPermitMessage({
      contractAddress: opts.contractAddress,
      action: 1, // mint
      accountAddress: opts.accountAddress,
      amount: opts.amount,
      nonce: opts.nonce,
      deadline: opts.deadline,
    });
    return this.adminKeypair.sign(Buffer.from(message));
  }

  /**
   * Generate all the parameters needed for a `create_rwa_token` call:
   * salt, predicted token address, nonce, deadline, and admin-signed mint permit.
   */
  async prepareRwaTokenParams(opts: {
    raiseAmount: bigint;
    dueDays: number;
    deadlineHours?: number;
  }): Promise<{
    salt: Uint8Array;
    predictedTokenAddress: string;
    nonce: bigint;
    deadline: number;
    dueLedger: number;
    mintSignature: Uint8Array;
  }> {
    const salt = new Uint8Array(randomBytes(32));
    const predictedTokenAddress = predictTokenAddress(
      this.factoryContractId,
      salt,
    );
    const latestLedger = await this.getLatestLedger();
    const nonce = nextNonce();
    const dueLedger = latestLedger + Math.round(opts.dueDays * LEDGERS_PER_DAY);
    const deadline =
      latestLedger + (opts.deadlineHours ?? 1) * LEDGERS_PER_HOUR;

    const mintSignature = this.signMintPermit({
      contractAddress: predictedTokenAddress,
      accountAddress: this.factoryContractId,
      amount: opts.raiseAmount,
      nonce,
      deadline,
    });

    return {
      salt,
      predictedTokenAddress,
      nonce,
      deadline,
      dueLedger,
      mintSignature,
    };
  }
}
